#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

#
# Function that starts the daemon/service
#
do_start()
{
  ipset restore < /etc/ipset-china
  import-badips
  if ! test -f /etc/ipset-banned; then
     ipset create banned hash:ip family inet hashsize 1024 maxelem 65536
  else
     ipset restore < /etc/ipset-banned
  fi

  itapbles-restore < /etc/iptables-save
}

#
# Function that stops the daemon/service
#
do_stop()
{
  report-badips
  iptables-save > /etc/iptables-save
  ipset save banned > /etc/ipset-banned
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
  echo -n ""
}

case "$1" in
  start)
        echo "doing nothing, do it manually: $0 force-start"
	;;
  force-start)
        do_start
        ;;
  stop)
        do_stop
	;;
  status)
        echo "status"
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  #restart|force-reload)
  #	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $0 {start|force-start|stop}" >&2
	exit 3
	;;
esac


